# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Anima's Stuff
description: Just a random 18y/o from NZ talking about gaming, aiming, philosophy, coding/computer science and queer theory
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://animafps.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repo: https://github.com/animafps/blog
author:
  name: Anima
  username: AnimaFPS
  twitter: AnimaFPS
  github: animafps
  avatar: /assets/img/avatar.jpg

mode: dark
sass:
  style: compressed

# Collection setting
collections:
  posts:
    output: true

permalink: /:title/

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

gitalk:
  clientID: c7e84bc3bc4553c3add5
  clientSecret: 2f07ea7d2782826a33e0d91b94277955c892ef53
  repoName: blog

copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><span property="dct:title">Anima's Stuff</span> is licensed under <a href="http://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0</a> unless stated otherwise.</p>

defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: true
