title: Anima's Stuff
description: Just a random 18y/o from NZ talking about gaming, aiming, philosophy, coding/computer science and queer theory
baseurl: ""
url: "https://animafps.xyz"
repo: https://github.com/animafps/blog
discordServer: https://discord.gg/aZbefuVXWJ
author:
  name: Anima
  username: AnimaFPS
  twitter: AnimaFPS
  mastodon: "@animadot"
  youtube: animafps
  github: animafps
  avatar: /assets/img/avatar.jpg

mode: dark
sass:
  style: compressed
  sass_dir: _sass

permalink: /:categories/:title/

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  math_engine: katex

copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><span property="dct:title">Anima's Stuff</span> is licensed under <a href="http://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0</a> unless stated otherwise.</p>

exclude:
  - readme.md

pwa:
  dest_js_directory: assets/js

katex:
  js_path: "{{ Gem::lib_path }}/assets/js"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
