title: Anima's Stuff
description: Just a random 18y/o from NZ talking about gaming, aiming, philosophy, coding/computer science and queer theory
baseurl: ""
url: "https://animafps.xyz"
repo: https://github.com/animafps/blog
author:
  name: Anima
  username: AnimaFPS
  twitter: AnimaFPS
  mastodon: "@animadot"
  youtube: animafps
  github: animafps
  avatar: /assets/img/avatar.jpg

mode: dark
sass:
  style: compressed
  sass_dir: _sass

permalink: /:categories/:title/

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  math_engine: katex

copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><span property="dct:title">Anima's Stuff</span> is licensed under <a href="http://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0</a> unless stated otherwise.</p>

exclude:
  - readme.md

pwa:
  dest_js_directory: assets/js
  precache_recent_posts_num: 50
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "/**/*.{css,js,json,xml}"
    - "/**/*.{ico,jpg,jpeg,png,svg}"
    - "/**/*.mp4"
    - "/**/*.html"
  precache_glob_ignores: # Optional
    - sw-register.js
    - "{401,403,404,500,legal-notice,privacy-policy}.html"
    - "/**/assets/js/workbox-v5.1.3/**/*"
    - "/**/*.xml"

katex:
  js_path: "{{ Gem::lib_path }}/assets/js"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
