name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Links:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - name: Use Node.js v16
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Wait for CF Pages
        id: cf-pages
        uses: WalshyDev/cf-pages-await@1a57fcdab04811dfbccb89c31294099151c31546 # tag=v1
        with:
          accountEmail: ${{ secrets.CF_ACCOUNT_EMAIL  }}
          apiKey: ${{ secrets.CF_API_KEY  }}
          accountId: '1d4cf1294df33e0483fffa84550d3052'
          project: 'blog'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Run BLC
        if: ${{ steps.cf-pages.outputs.success }}
        run: npm exec --package=broken-link-checker -- blc -ro -f '${{ steps.cf-pages.outputs.url }}'

  A11y:
    name: A11y
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - name: Use Node.js v16
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Wait for CF Pages
        id: cf-pages
        uses: WalshyDev/cf-pages-await@1a57fcdab04811dfbccb89c31294099151c31546 # tag=v1
        with:
          accountEmail: ${{ secrets.CF_ACCOUNT_EMAIL  }}
          apiKey: ${{ secrets.CF_API_KEY  }}
          accountId: '1d4cf1294df33e0483fffa84550d3052'
          project: 'blog'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Run pa11ly-ci
        if: ${{ steps.cf-pages.outputs.success }}
        run: npx pa11y-ci --sitemap '${{ steps.cf-pages.outputs.url }}/sitemap.xml' --sitemap-find 'https://animafps.xyz' --sitemap-replace '${{ steps.cf-pages.outputs.url }}' 
